audio: asoc : Don't pass endianess and mode as argument to pcm format v3 function
Endianess and mode should not be passed as arguments to q6asm_media_format_block_pcm_format_support_v3  function
Hence following error has been fixed:
../techpack/audio/asoc/msm-compress-q6-v2.c:1046:6: error: too many arguments to function call, expected 8, have 10
                                        ASM_LITTLE_ENDIAN,
                                        ^~~~~~~~~~~~~~~~~~
../techpack/audio/include/dsp/q6asm-v2.h:111:27: note: expanded from macro 'ASM_LITTLE_ENDIAN'
#define ASM_LITTLE_ENDIAN 0
                          ^
../techpack/audio/include/dsp/q6asm-v2.h:510:5: note: 'q6asm_media_format_block_pcm_format_support_v3' declared here
int q6asm_media_format_block_pcm_format_support_v3(struct audio_client *ac,
    ^
1 error generated.